config/routes.rb
Rails.application.routes.draw do
  resources :pictures do
    resources :copies
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pictures#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/copy.rb
class Copy < ApplicationRecord
  belongs_to :picture

  has_one_attached :image

  validates :name, :image, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :copies

  has_one_attached :image

  validates :title, :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  before_action :set_picture
  before_action :set_copy, only: [:show, :edit, :update, :destroy]

  # GET /copies
  # GET /copies.json
  def index
    @copies = @picture.copies
  end

  # GET /copies/1
  # GET /copies/1.json
  def show
  end

  # GET /copies/new
  def new
    @copy = @picture.copies.build
  end

  # GET /copies/1/edit
  def edit
  end

  # POST /copies
  # POST /copies.json
  def create
    @copy = @picture.copies.new(copy_params)

    respond_to do |format|
      if @copy.save
        format.html { redirect_to @copy.picture, notice: 'Copy was successfully created.' }
        format.json { render :show, status: :created, location: @copy }
      else
        format.html { render :new }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /copies/1
  # PATCH/PUT /copies/1.json
  def update
    respond_to do |format|
      if @copy.update(copy_params)
        format.html { redirect_to @copy.picture, notice: 'Copy was successfully updated.' }
        format.json { render :show, status: :ok, location: @copy }
      else
        format.html { render :edit }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copies/1
  # DELETE /copies/1.json
  def destroy
    @copy.destroy
    respond_to do |format|
      format.html { redirect_to copies_url, notice: 'Copy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:picture_id])
    end

    def set_copy
      @copy = Copy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def copy_params
      params.fetch(:copy, {}).permit(:image, :name, :picture_id)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.fetch(:picture, {}).permit(:image, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/copies/_form.html.erb
<%= form_with(model: [copy.picture, copy], url: picture_copies_path(copy.picture_id), local: true) do |form| %>
  <% if copy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(copy.errors.count, "error") %> prohibited this copy from being saved:</h2>

      <ul>
        <% copy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :picture_id, value: copy.picture_id %>
  <div class="w-full">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-field" %>
  </div>

  <div class="w-full">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-field" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn" %>
    <%= link_to 'Back', pictures_path, class: "btn" %>
  </div>
<% end %>

app/views/copies/edit.html.erb
<div class="mx-auto max-w-4xl w-full leading-loose p-4">
  <h2>
    Editing Copy
  </h2>
  <%= render 'form', copy: @copy %>
</div>

<%= link_to 'Show', @copy %> |
<%= link_to 'Back', copies_path %>

app/views/copies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Copies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @copies.each do |copy| %>
      <tr>
        <td><%= link_to 'Show', copy %></td>
        <td><%= link_to 'Edit', edit_copy_path(copy) %></td>
        <td><%= link_to 'Destroy', copy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Copy', new_copy_path %>

app/views/copies/new.html.erb
<div class="mx-auto max-w-4xl w-full leading-loose p-4">
  <h2>
    New Copy
  </h2>
  <%= render 'form', copy: @copy %>
</div>

app/views/copies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_copy_path(@copy) %> |
<%= link_to 'Back', copies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PictureCopy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="pt-20">
      <header>
        <nav class="fixed top-0 flex w-full bg-white p-6">
          <div class="flex-1 text-gray-700">
            <%= link_to root_path do %>
              PictureCopy
            <% end %>
          </div>

          <div class="flex-1 text-right">
            <%= link_to "Add Picture", new_picture_path, class: "block text-gray-700 hover:text-black" %>
          </div>
        </nav>
      </header>
      <div class="flex flex-wrap">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-field" %>
  </div>

  <div class="w-full">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-field" %>
  </div>

  <div class="w-full">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-field" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn" %>
    <%= link_to 'Back', pictures_path, class: "btn" %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div class="w-full md:w-1/2">
  <%= image_tag picture.image, title: picture.title %>
</div>
<div class="w-full md:w-1/2">
  <div class="grid grid-cols-2 lg:grid-cols-4">
    <%= link_to new_picture_copy_path(picture) do %>
      <div class="flex items-center justify-center">
        <div class="font-bold text-6xl">
          +
        </div>
      </div>
    <% end %>
    <% picture.copies.each do |copy| %>
      <%= image_tag copy.image, title: copy.name %>
    <% end %>
  </div>
</div>
<div class="w-full p-6 pb-12">
  <strong>
    <%= picture.title %>
  </strong>
  &#8226;
  <%= picture.description %>
</div>

app/views/pictures/edit.html.erb
<div class="mx-auto max-w-4xl w-full leading-loose p-4">
  <h2>
    Editing Picture
  </h2>
  <%= render 'form', picture: @picture %>
</div>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<%= render partial: "picture", collection: @pictures %>

app/views/pictures/new.html.erb
<div class="mx-auto max-w-4xl w-full leading-loose p-4">
  <h2>
    New Picture
  </h2>
  <%= render 'form', picture: @picture %>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Edit', edit_picture_path(@picture) %> |
  <%= link_to 'Back', pictures_path %>
</p>

<h1>
  <%= @picture.title %>
</h1>
<p>
  <%= @picture.description %>
</p>
<%= render "picture", picture: @picture %>